spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
#  kafka:
#    consumer:
#      group-id: kafka1
#      auto-offset-reset: earliest
#      bootstrap-servers:
#        localhost: 9092
#    productor:
#      bootstrap-servers:
#        localhost: 9092
#        key-serializer: org.apache.kafka.common.serialization.StringSerializer
#        value-serializer: org.apache.kafka.common.serialization.StringSerializer

#  security:
#    basic:
#      enabled: true

  cache:
    jcache:
      config: classpath:cache/ehcache.xml

  mybatis-plus:
    type-aliases-package: com.example.spring.entity
  
server:
  port: 8081
  address: localhost
